### ISSUE TITLE
Rust Anthology 1

### ISSUE THREAD

**Issue by brson** [brson/rust-anthology#2]
This is the tracking issue for version 1 of Rust Anthology. Each of these steps leads to an additional tracking bug. See those bugs for more information on how to help.

Current work is mostly in preliminary chapter selection.
## Book preparation phases
- [ ] [Preliminary chapter selection](https://github.com/brson/rust-anthology/issues/3)
- [ ] [Acquire author permission and licensing](https://github.com/brson/rust-anthology/issues/5)
- [ ] [Final selection and chapter organization](https://github.com/brson/rust-anthology/issues/9)
- [ ] [Chapter editing](https://github.com/brson/rust-anthology/issues/6)
- [ ] [Testing]
- [ ] [Author descriptions]
- [ ] [Final author review]
- [ ] [Print publication](https://github.com/brson/rust-anthology/issues/4)
## Other work
- [ ] [Deploy via Travis](https://github.com/brson/rust-anthology/issues/1)
- [ ] [Write introductory text]
- [ ] [More robust testing](https://github.com/brson/rust-anthology/issues/8)
- [ ] [Get footnotes working](https://github.com/brson/rust-anthology/issues/7)
